services:
  app:
    build: .
    container_name: webide-spring-be
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_H2_CONSOLE_ENABLED=true
    volumes:
      - ./src:/app/src
      - ./build.gradle:/app/build.gradle
      - ./settings.gradle:/app/settings.gradle
      - ./gradle:/app/gradle
      - ./gradlew:/app/gradlew
    depends_on:
      - mysql
    networks:
      - webide-network

  mysql:
    image: mysql:8.0
    container_name: webide-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: webide_db
      MYSQL_USER: webide_user
      MYSQL_PASSWORD: webide_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - webide-network

volumes:
  mysql_data:

networks:
  webide-network:
    driver: bridge 